project:
  type: seedcase-theme

website:
  title: "Seedcase Project"
  favicon: "/images/logo.svg"
  site-url: "https://seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/seedcase-project"
  page-footer:
    center:
      - text: "License: CC-BY 4.0"
        href: LICENSE.md
  page-navigation: true
  navbar:
    pinned: true
    logo: "/images/logo.svg"
    right:
      - text: "About"
        href: about/index.md
      - text: "Community"
        href: community/index.qmd
      - text: "Design"
        href: design/index.md
    tools:
      - icon: github
        href: "https://github.com/seedcase-project/seedcase-project"
  sidebar:
    - id: community
      title: "Community"
      pinned: true
      style: "floating"
      align: left
      collapse-level: 1
      contents:
        - community/index.qmd
        - section: "Contributing"
          contents:
            - text: "Overview"
              href: community/CONTRIBUTING.md
            - auto: community/guide-entries
            - auto: community/decisions
            - text: "Code of Conduct"
              href: "https://github.com/seedcase-project/.github/blob/main/CODE_OF_CONDUCT.md"
        - community/blocks.qmd
        - community/roadmap.qmd
    - id: design
      title: "Design"
      pinned: true
      style: "floating"
      align: left
      collapse-level: 1
      contents:
        - design/index.md
        - auto: design/software-architecture/
    - id: about
      title: "About"
      pinned: true
      style: "floating"
      align: left
      collapse-level: 1
      contents:
      - about/index.md
      - text: "History"
        href: about/history/index.md
      # - text: "Mission"
      #   href: about/mission.md
      - text: "Team Members"
        href: about/team/index.md


bibliography: "includes/references.bib"

# format:
#   seedcase-theme-html:
    # include-before-body:
      # - "includes/site-counter.html"
      # - "includes/contribute.html"

editor:
  markdown:
    wrap: 72
    canonical: true

execute:
  echo: false
